openapi: 3.0.3
info:
  title: DND Tracker Combat API
  version: 1.0.0
  description: Combat session management and real-time combat operations

paths:
  /api/combat/start:
    post:
      summary: Start new combat session
      description: Creates a new combat session from an encounter
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - encounterId
              properties:
                encounterId:
                  type: string
                initiativeRolls:
                  type: array
                  items:
                    type: object
                    properties:
                      participantId:
                        type: string
                      roll:
                        type: integer
                        minimum: 1
                        maximum: 20
      responses:
        '201':
          description: Combat session started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CombatSession'
        '400':
          description: Invalid encounter or participant data
        '403':
          description: Participant limit exceeded for tier

  /api/combat/{sessionId}:
    get:
      summary: Get combat session state
      description: Returns current combat session with all participant data
      security:
        - BearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Combat session retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CombatSession'
        '404':
          description: Combat session not found

    delete:
      summary: End combat session
      description: Ends the combat session and saves final state
      security:
        - BearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Combat session ended successfully
        '404':
          description: Combat session not found

  /api/combat/{sessionId}/initiative:
    put:
      summary: Update initiative order
      description: Modifies initiative order with optional manual overrides
      security:
        - BearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                updates:
                  type: array
                  items:
                    type: object
                    properties:
                      participantId:
                        type: string
                      newRoll:
                        type: integer
                        minimum: 1
                        maximum: 20
                      manualOverride:
                        type: integer
                        description: Manual position override
      responses:
        '200':
          description: Initiative order updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  initiative:
                    type: array
                    items:
                      $ref: '#/components/schemas/InitiativeEntry'

  /api/combat/{sessionId}/turn:
    post:
      summary: Advance to next turn
      description: Advances combat to the next participant's turn
      security:
        - BearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Turn advanced successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  currentTurn:
                    $ref: '#/components/schemas/CurrentTurn'
                  triggeredLairActions:
                    type: array
                    items:
                      $ref: '#/components/schemas/LairAction'

  /api/combat/{sessionId}/hp:
    put:
      summary: Modify participant HP
      description: Apply damage or healing to a participant with undo support
      security:
        - BearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - participantId
                - change
                - type
              properties:
                participantId:
                  type: string
                change:
                  type: integer
                  description: Amount of change (positive for healing, negative for damage)
                type:
                  type: string
                  enum: ['damage', 'healing', 'temporary']
                source:
                  type: string
                  description: Source of damage/healing for history tracking
      responses:
        '200':
          description: HP modified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  participant:
                    $ref: '#/components/schemas/CombatParticipant'
                  historyEntry:
                    $ref: '#/components/schemas/HistoryEntry'

  /api/combat/{sessionId}/status-effects:
    post:
      summary: Apply status effect
      description: Adds a status effect to a participant
      security:
        - BearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - participantId
                - effectName
                - duration
              properties:
                participantId:
                  type: string
                effectName:
                  type: string
                description:
                  type: string
                duration:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: ['rounds', 'minutes', 'hours', 'until_save', 'concentration', 'permanent']
                    value:
                      type: integer
                    endTrigger:
                      type: string
                      enum: ['start_of_turn', 'end_of_turn', 'start_of_round', 'end_of_round']
                source:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: ['spell', 'ability', 'environmental', 'manual']
                    name:
                      type: string
                    casterId:
                      type: string
      responses:
        '201':
          description: Status effect applied successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusEffect'

    delete:
      summary: Remove status effect
      description: Removes a specific status effect from a participant
      security:
        - BearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
        - name: participantId
          in: query
          required: true
          schema:
            type: string
        - name: effectId
          in: query
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Status effect removed successfully

  /api/combat/{sessionId}/lair-actions:
    post:
      summary: Trigger lair action
      description: Executes a lair action and updates encounter state
      security:
        - BearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - actionId
              properties:
                actionId:
                  type: string
                selectedOption:
                  type: string
                  description: For choice-based lair actions
                customDescription:
                  type: string
                  description: DM custom description override
      responses:
        '200':
          description: Lair action executed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  affectedParticipants:
                    type: array
                    items:
                      type: string
                  nextTrigger:
                    type: integer

  /api/combat/{sessionId}/undo:
    post:
      summary: Undo last action
      description: Reverts the most recent undoable action
      security:
        - BearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - historyEntryId
              properties:
                historyEntryId:
                  type: string
      responses:
        '200':
          description: Action undone successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  restoredState:
                    type: object
                  undoneAction:
                    $ref: '#/components/schemas/HistoryEntry'

components:
  schemas:
    CombatSession:
      type: object
      properties:
        id:
          type: string
        encounterId:
          type: string
        userId:
          type: string
        status:
          type: string
          enum: ['preparing', 'active', 'paused', 'completed']
        initiative:
          type: array
          items:
            $ref: '#/components/schemas/InitiativeEntry'
        currentTurn:
          $ref: '#/components/schemas/CurrentTurn'
        participants:
          type: array
          items:
            $ref: '#/components/schemas/CombatParticipant'
        lairActions:
          $ref: '#/components/schemas/LairActionsState'
        history:
          type: array
          items:
            $ref: '#/components/schemas/HistoryEntry'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    InitiativeEntry:
      type: object
      properties:
        participantId:
          type: string
        participantType:
          type: string
          enum: ['character', 'monster']
        name:
          type: string
        initiativeRoll:
          type: integer
        initiativeTotal:
          type: integer
        dexterity:
          type: integer
        manualOverride:
          type: integer

    CurrentTurn:
      type: object
      properties:
        participantId:
          type: string
        roundNumber:
          type: integer
        turnIndex:
          type: integer

    CombatParticipant:
      type: object
      properties:
        id:
          type: string
        sourceId:
          type: string
        type:
          type: string
          enum: ['character', 'monster']
        name:
          type: string
        stats:
          type: object
          properties:
            armorClass:
              type: integer
            hitPointsMax:
              type: integer
            hitPointsCurrent:
              type: integer
            temporaryHP:
              type: integer
        statusEffects:
          type: array
          items:
            $ref: '#/components/schemas/StatusEffect'
        notes:
          type: string

    StatusEffect:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        type:
          type: string
          enum: ['condition', 'spell', 'ability', 'environmental']
        duration:
          type: object
          properties:
            type:
              type: string
              enum: ['rounds', 'minutes', 'hours', 'until_save', 'concentration', 'permanent']
            remaining:
              type: integer
            endTrigger:
              type: string
              enum: ['start_of_turn', 'end_of_turn', 'start_of_round', 'end_of_round']
        effects:
          type: object
          properties:
            modifiers:
              type: array
              items:
                type: object
                properties:
                  stat:
                    type: string
                  value:
                    type: integer
                  type:
                    type: string
                    enum: ['bonus', 'penalty', 'advantage', 'disadvantage']
            restrictions:
              type: array
              items:
                type: string
        source:
          type: object
          properties:
            type:
              type: string
              enum: ['spell', 'ability', 'environmental', 'manual']
            name:
              type: string
            casterId:
              type: string
        appliedAt:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time

    LairActionsState:
      type: object
      properties:
        isActive:
          type: boolean
        nextTrigger:
          type: integer
        availableActions:
          type: array
          items:
            $ref: '#/components/schemas/LairAction'

    LairAction:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        used:
          type: boolean

    HistoryEntry:
      type: object
      properties:
        id:
          type: string
        timestamp:
          type: string
          format: date-time
        action:
          type: string
        participantId:
          type: string
        details:
          type: object
        canUndo:
          type: boolean

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT