openapi: 3.0.3
info:
  title: User Profile API
  description: API endpoints for managing user profile and D&D preferences
  version: 1.0.0

paths:
  /api/users/{id}/profile:
    get:
      summary: Get user profile
      description: Retrieves the current user's profile including D&D preferences and usage metrics
      operationId: getUserProfile
      security:
        - clerkAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: User ID (must match authenticated user)
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Unauthorized - Invalid or missing authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User ID does not match authenticated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    patch:
      summary: Update user profile
      description: |
        Updates user profile with D&D preferences and optional fields.
        All fields are optional - only provided fields are updated.
      operationId: updateUserProfile
      security:
        - clerkAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: User ID (must match authenticated user)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileUpdateRequest'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Validation error - Invalid field values
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          description: Unauthorized - Invalid or missing authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User ID does not match authenticated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    clerkAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Clerk session JWT token

  schemas:
    UserProfile:
      type: object
      required:
        - id
        - email
        - username
        - firstName
        - lastName
        - role
        - subscriptionTier
        - timezone
        - dndEdition
        - profileSetupCompleted
      properties:
        id:
          type: string
          example: "507f1f77bcf86cd799439011"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        username:
          type: string
          example: "johndoe"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        displayName:
          type: string
          nullable: true
          maxLength: 100
          example: "Dungeon Master John"
        role:
          type: string
          enum: [user, admin]
          example: "user"
        subscriptionTier:
          type: string
          enum: [free, seasoned, expert, master, guild]
          example: "free"
        timezone:
          type: string
          example: "America/New_York"
        dndEdition:
          type: string
          maxLength: 50
          example: "5th Edition"
        experienceLevel:
          type: string
          enum: [new, beginner, intermediate, experienced, veteran]
          nullable: true
          example: "intermediate"
        primaryRole:
          type: string
          enum: [dm, player, both]
          nullable: true
          example: "dm"
        profileSetupCompleted:
          type: boolean
          example: true
        preferences:
          $ref: '#/components/schemas/UserPreferences'
        usageMetrics:
          $ref: '#/components/schemas/UsageMetrics'
        createdAt:
          type: string
          format: date-time
          example: "2025-09-30T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-09-30T14:30:00Z"

    ProfileUpdateRequest:
      type: object
      properties:
        displayName:
          type: string
          nullable: true
          maxLength: 100
          example: "Dungeon Master John"
        timezone:
          type: string
          example: "America/New_York"
        dndEdition:
          type: string
          maxLength: 50
          example: "5th Edition"
        experienceLevel:
          type: string
          enum: [new, beginner, intermediate, experienced, veteran]
          nullable: true
          example: "intermediate"
        primaryRole:
          type: string
          enum: [dm, player, both]
          nullable: true
          example: "dm"
        profileSetupCompleted:
          type: boolean
          example: true
        preferences:
          $ref: '#/components/schemas/UserPreferencesUpdate'

    UserPreferences:
      type: object
      required:
        - theme
        - emailNotifications
        - browserNotifications
        - timezone
        - language
        - diceRollAnimations
        - autoSaveEncounters
      properties:
        theme:
          type: string
          enum: [light, dark, system]
          example: "system"
        emailNotifications:
          type: boolean
          example: true
        browserNotifications:
          type: boolean
          example: false
        timezone:
          type: string
          example: "UTC"
        language:
          type: string
          example: "en"
        diceRollAnimations:
          type: boolean
          example: true
        autoSaveEncounters:
          type: boolean
          example: true

    UserPreferencesUpdate:
      type: object
      properties:
        theme:
          type: string
          enum: [light, dark, system]
        emailNotifications:
          type: boolean
        browserNotifications:
          type: boolean
        timezone:
          type: string
        language:
          type: string
        diceRollAnimations:
          type: boolean
        autoSaveEncounters:
          type: boolean

    UsageMetrics:
      type: object
      required:
        - sessionsCount
        - charactersCreatedCount
        - campaignsCreatedCount
      properties:
        sessionsCount:
          type: integer
          minimum: 0
          example: 42
        charactersCreatedCount:
          type: integer
          minimum: 0
          example: 8
        campaignsCreatedCount:
          type: integer
          minimum: 0
          example: 2
        metricsLastUpdated:
          type: string
          format: date-time
          nullable: true
          example: "2025-09-30T14:30:00Z"

    Error:
      type: object
      required:
        - success
        - error
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: "User not found"

    ValidationError:
      type: object
      required:
        - success
        - error
        - errors
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: "Validation failed"
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                example: "displayName"
              message:
                type: string
                example: "Display name cannot exceed 100 characters"
